name: uwu_pixel_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0

dev_dependencies:
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  build_runner: ^2.4.6
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
